spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: local

server:
  port: 5000

# REST client
restClient:
  productUrl: http://localhost:3001/product

# LOGGING ----------
logging:
  level:
    root: INFO
# debug: false
# trace: false
